
services:
  ytsum:
    build: .
    container_name: ytsum
    ports:
      - "5050:5050"
    env_file:
      - .env
    volumes:
      - ./data:/app/data  # Optional: for persistent data storage
      - ./out:/app/out
    restart: unless-stopped
    networks:
      - traefik

networks:
  traefik:
    name: traefik
    external: true
