name: Docker Image CI

on:
  push:
    tags:
      - v*
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Docker login
      run: docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ytsum:$(date +%s) --tag ytsum:latest
    - name: docker push
      run: docker push ghcr.io/seyar/ytsum:$(date +%s); docker push ghcr.io/seyar/ytsum:$(date +%s)
