name: post commit

on:
  push:
    branches:
      - ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Tests
      run: python -m unittest /app/test_app.py -v
